import React from 'react';
import { StoryboardPanel } from '../types';

interface PrintLayoutProps {
  panels: StoryboardPanel[];
  title?: string;
  className?: string; // Allow parent to control positioning
}

const PrintLayout: React.FC<PrintLayoutProps> = ({ panels, title = "Storyboard Script", className = "" }) => {
  // Chunk panels into groups of 3 for each page
  const pages = [];
  for (let i = 0; i < panels.length; i += 3) {
    pages.push(panels.slice(i, i + 3));
  }

  if (panels.length === 0) return null;

  return (
    // We pass the ID 'print-root' here. The parent controls visibility/position via className.
    <div id="print-root" className={`w-[210mm] bg-white text-black ${className}`}>
      {pages.map((pagePanels, pageIndex) => (
        <div 
          key={pageIndex} 
          className="relative w-[210mm] h-[297mm] mx-auto bg-white p-[10mm] box-border flex flex-col"
          style={{ pageBreakAfter: 'always' }}
        >
          {/* Header */}
          <div className="flex justify-between items-end border-b-2 border-black pb-2 mb-4">
            <div>
              <h1 className="text-xl font-bold uppercase tracking-wider">{title}</h1>
              <p className="text-sm text-gray-600">Generated by Script2Story</p>
            </div>
            <div className="text-right">
              <div className="text-lg font-bold">Page {pageIndex + 1} of {pages.length}</div>
              <div className="text-xs text-gray-500">{new Date().toLocaleDateString()}</div>
            </div>
          </div>

          {/* Panels Grid */}
          <div className="flex-grow flex flex-col gap-6">
            {pagePanels.map((panel) => (
              <div key={panel.id} className="flex flex-row gap-4 border border-gray-800 p-2 h-[80mm]">
                
                {/* Left: Depiction Box (Visual) */}
                <div className="w-1/2 flex flex-col gap-1">
                  <div className="text-xs font-bold uppercase tracking-wider text-gray-500">Visual / Depiction</div>
                  <div className="flex-grow border-2 border-gray-300 rounded bg-gray-50 relative">
                     <span className="absolute top-2 left-2 text-xs text-gray-400 font-mono">SEQ #{panel.sequenceNumber}</span>
                     {/* Empty space for drawing */}
                  </div>
                </div>

                {/* Right: Details Boxes */}
                <div className="w-1/2 flex flex-col gap-2">
                  
                  {/* Script Segment (Read Only ref) */}
                  <div className="h-1/5">
                     <div className="text-[10px] font-bold uppercase text-gray-500">Script Source</div>
                     <div className="text-xs italic bg-gray-100 p-1 border border-gray-200 h-full overflow-hidden leading-tight">
                        "{panel.scriptSegment.length > 150 ? panel.scriptSegment.substring(0, 150) + '...' : panel.scriptSegment}"
                     </div>
                  </div>

                  {/* Grid for writing details */}
                  <div className="h-4/5 grid grid-cols-2 gap-2">
                    {/* Visual Prompt / Action */}
                    <div className="col-span-2 flex flex-col">
                      <div className="text-[10px] font-bold uppercase text-gray-500">Visual Prompt / Action</div>
                      <div className="flex-grow border-b border-gray-300 border-dashed relative overflow-hidden">
                        <span className="text-xs font-serif text-black whitespace-pre-wrap">{panel.actionNotes}</span>
                      </div>
                    </div>

                    {/* Environment */}
                    <div className="flex flex-col">
                      <div className="text-[10px] font-bold uppercase text-gray-500">Environment</div>
                      <div className="flex-grow border-b border-gray-300 border-dashed">
                         <span className="text-xs font-serif text-black">{panel.environmentNotes}</span>
                      </div>
                    </div>

                    {/* Mood */}
                    <div className="flex flex-col">
                      <div className="text-[10px] font-bold uppercase text-gray-500">Mood</div>
                      <div className="flex-grow border-b border-gray-300 border-dashed">
                        <span className="text-xs font-serif text-black">{panel.moodNotes}</span>
                      </div>
                    </div>

                    {/* Character */}
                    <div className="flex flex-col">
                      <div className="text-[10px] font-bold uppercase text-gray-500">Character(s)</div>
                      <div className="flex-grow border-b border-gray-300 border-dashed">
                         <span className="text-xs font-serif text-black">{panel.characterNotes}</span>
                      </div>
                    </div>

                    {/* Expression */}
                    <div className="flex flex-col">
                      <div className="text-[10px] font-bold uppercase text-gray-500">Expression</div>
                      <div className="flex-grow border-b border-gray-300 border-dashed">
                         <span className="text-xs font-serif text-black">{panel.expressionNotes}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Footer Notes Space */}
          <div className="mt-auto pt-2 border-t border-gray-300">
             <div className="text-[10px] text-gray-400 uppercase">Notes</div>
             <div className="h-8 border-b border-dotted border-gray-300"></div>
          </div>
        </div>
      ))}
    </div>
  );
};

export default PrintLayout;